"""Self-evaluation module for agent responses."""

import os
import json
import logging
from openai import OpenAI
from .utils import extract_citations
from .traceability import TraceabilityTracker
from .types import EvaluationResult, CitationValidationResult

logger = logging.getLogger(__name__)


def evaluate_response(
    answer: str,
    tracker: TraceabilityTracker,
    user_query: str | None = None,
    citation_validation: 'CitationValidationResult | None' = None
) -> EvaluationResult:
    """
    Evaluate the agent's response using LLM.

    Args:
        answer: The final answer generated by the agent
        tracker: TraceabilityTracker with sources and reasoning
        user_query: The user's query (optional, improves relevance evaluation)
        citation_validation: Citation validation results (optional, enhances accuracy evaluation)

    Returns:
        Evaluation dict with scores and feedback
    """
    client: OpenAI = OpenAI(
        api_key=os.getenv("OPENAI_API_KEY"),
        base_url=os.getenv("OPENAI_BASE_URL")
    )

    # Extract citations from answer to determine which sources to include
    cited_indices: list[int] = extract_citations(answer)

    # Validate citations - catches hallucinated source numbers
    invalid_citations: list[int] = [idx for idx in cited_indices if idx < 1 or idx > len(tracker.sources)]
    if invalid_citations:
        logger.warning(f"Invalid citations detected: {invalid_citations} (valid range: 1-{len(tracker.sources)})")

    # Build evaluation prompt with only cited sources
    sources_summary: str
    if cited_indices:
        # Include only cited sources - reduces token usage and focuses evaluation
        sources_summary = "\n".join([
            f"[{idx}] {tracker.sources[idx-1].get('title', 'N/A')} ({tracker.sources[idx-1].get('source', 'N/A')}, {tracker.sources[idx-1].get('date', 'N/A')})"
            for idx in cited_indices
            if 1 <= idx <= len(tracker.sources)
        ])
    else:
        # Fallback for answers without citations - use first 10 sources
        sources_summary = "\n".join([
            f"- {s.get('title', 'N/A')} ({s.get('source', 'N/A')}, {s.get('date', 'N/A')})"
            for s in tracker.sources[:10]
        ])

    # Include user query if provided
    query_section: str = ""
    if user_query:
        query_section = f"""USER QUERY:
{user_query}

"""

    # Build citation validation details if available
    validation_section: str = ""
    if citation_validation:
        claims = citation_validation.get("claims", [])
        if claims:
            validation_lines = ["CITATION VALIDATION RESULTS:"]
            for i, claim_data in enumerate(claims, 1):
                claim_text = claim_data.get("claim", "")
                citations = claim_data.get("citations", [])
                invalid_cites = claim_data.get("invalid_citations", [])
                validation_result = claim_data.get("validation_result")

                validation_lines.append(f"\nClaim {i}: \"{claim_text}\" {citations}")

                # Show invalid citations
                if invalid_cites:
                    validation_lines.append(f"  - INVALID CITATIONS: {invalid_cites} (out of valid range)")

                # Show LLM validation result
                if validation_result:
                    supported = validation_result.get("supported")
                    confidence = validation_result.get("confidence", "")
                    explanation = validation_result.get("explanation", "")

                    status = "SUPPORTED" if supported else "NOT SUPPORTED"
                    validation_lines.append(f"  - Validation: {status} ({confidence} confidence)")
                    if explanation:
                        validation_lines.append(f"  - Explanation: {explanation}")

            validation_section = "\n".join(validation_lines) + "\n\n"

    evaluation_prompt: str = f"""Evaluate this financial news analysis response based on the criteria below.

{query_section}ANSWER:
{answer}

SOURCES USED:
{sources_summary if sources_summary else "No sources"}
{validation_section}
EVALUATION CRITERIA (rate each 1-10, where 10 is excellent):
1. Accuracy: Does the information in the answer match the sources provided? Are all citations [1], [2], etc. valid and supported by the listed sources?
2. Relevance: Does the answer directly address the user's query? Are the sources relevant?
3. Coherence: Does the storyline flow logically and make sense?
4. Reasonableness: Is the future impact analysis plausible and well-reasoned?

Respond with ONLY a JSON object in this exact format:
{{
  "accuracy": <score 1-10>,
  "relevance": <score 1-10>,
  "coherence": <score 1-10>,
  "reasonableness": <score 1-10>,
  "feedback": "<brief explanation of scores>"
}}"""

    try:
        response = client.chat.completions.create(
            model=os.getenv("OPENAI_MODEL", "gpt-5.5"),
            messages=[
                {"role": "system", "content": "You are an expert evaluator of financial analysis quality. Respond only with valid JSON."},
                {"role": "user", "content": evaluation_prompt}
            ],
            temperature=0.3,
            max_tokens=500
        )

        # Parse evaluation
        eval_text: str = response.choices[0].message.content.strip() if response.choices[0].message.content else "{}"

        # Extract JSON if wrapped in markdown - LLMs sometimes add code fences despite instructions
        if "```json" in eval_text:
            eval_text = eval_text.split("```json")[1].split("```")[0].strip()
        elif "```" in eval_text:
            eval_text = eval_text.split("```")[1].split("```")[0].strip()

        evaluation: EvaluationResult = json.loads(eval_text)

        # Calculate overall score
        scores: list[int] = [
            evaluation.get("accuracy", 3),
            evaluation.get("relevance", 3),
            evaluation.get("coherence", 3),
            evaluation.get("reasonableness", 3)
        ]
        evaluation["overall"] = round(sum(scores) / len(scores), 2)

        return evaluation

    except Exception as e:
        logger.error(f"Evaluation error: {e}")
        # Return default evaluation on error
        return {
            "accuracy": 3,
            "relevance": 3,
            "coherence": 3,
            "reasonableness": 3,
            "overall": 3.0,
            "feedback": f"Evaluation failed: {str(e)}"
        }
